/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('created' | 'payment_pending' | 'paid' | 'payment_failed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    pages: Page;
    posts: Post;
    categories: Category;
    testimonials: Testimonial;
    menus: Menu;
    'course-progress': CourseProgress;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    forms: Form;
    'form-submissions': FormSubmission;
    users: User;
    'webhook-events': WebhookEvent;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'course-progress': CourseProgressSelect<false> | CourseProgressSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'webhook-retry': TaskWebhookRetry;
      'order-poll': TaskOrderPoll;
      'invoice-issue': TaskInvoiceIssue;
      'storno-issue': TaskStornoIssue;
      'corrective-invoice-issue': TaskCorrectiveInvoiceIssue;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Az oldalon használt képek. Feltöltés után bármelyik oldalról kiválaszthatók.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A kép szöveges leírása — kötelező, a képernyőolvasók és a Google miatt. Írd le egy mondatban, mi látszik a képen.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Önálló aloldalak (pl. Rólunk, Szolgáltatások). A kezdőlap tartalma a „kezdolap" webcímű oldalon él.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Az oldal címe — ez jelenik meg a lap tetején és a böngészőfülön.
   */
  title: string;
  /**
   * A cím webcímes alakja, magától kitöltődik (ékezetek nélkül, kötőjelekkel). Csak akkor írd át, ha tudod, mit csinálsz — a régi webcím ilyenkor megszűnik működni.
   */
  slug: string;
  /**
   * Pár mondatos összefoglaló; a Google találati listáján is ez jelenhet meg.
   */
  excerpt?: string | null;
  /**
   * Az oldal szövege. A felső eszköztárral formázhatsz, listázhatsz, linkelhetsz.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Az oldal „építőkockás" része. A lap alján lévő + gombbal veszel fel új szekciót; a sorok bal szélén lévő fogantyúval fogd-és-vidd módszerrel átrendezed őket; a szekción belüli Szekció-beállítások → Látható pipával pedig elrejtheted az egyiket úgy, hogy a tartalma megmarad. Ha üresen hagyod, az oldal a megszokott módon jelenik meg — semmi nem vész el.
   */
  layout?:
    | (
        | BlockFilmHero
        | BlockCredsStrip
        | BlockCourseCards
        | BlockFreeSos
        | BlockPressLogos
        | BlockWelcome
        | BlockUsps
        | BlockStates
        | BlockServices
        | BlockAbout
        | BlockHowItWorks
        | BlockTestimonials
        | BlockKnowledge
        | BlockFaq
        | BlockRichText
        | BlockCtaBanner
      )[]
    | null;
  /**
   * Az oldal tetején megjelenő nagy kép (nem kötelező).
   */
  heroImage?: (number | null) | Media;
  /**
   * Ha üresen hagyod, a Google a fenti címet használja.
   */
  seoTitle?: string | null;
  /**
   * A Google találati listáján megjelenő rövid leírás (kb. 150 karakter).
   */
  seoDescription?: string | null;
  /**
   * Ez a kép jelenik meg, ha valaki Facebookon vagy Messengeren megosztja az oldalt.
   */
  ogImage?: (number | null) | Media;
  status: 'draft' | 'published';
  /**
   * Az első közzétételkor magától kitöltődik. Csak akkor írd át, ha más dátumot akarsz mutatni.
   */
  publishedAt?: string | null;
  /**
   * A lista- és menürendezéshez használt sorszám (kisebb = előrébb).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFilmHero".
 */
export interface BlockFilmHero {
  /**
   * A lap legfontosabb mondata, ez a legnagyobb betűs szöveg az oldal tetején. Egy tömör állítás működik a legjobban.
   */
  title: string;
  /**
   * A cím alatti 1–3 mondat: kinek és miben segít a Kineticare.
   */
  lead?: string | null;
  /**
   * Rövid szavak a hero alatt, amik megmutatják, mivel foglalkozunk (pl. Kéz, Csukló, Könyök, Váll). Nem kötelező.
   */
  tags?:
    | {
        /**
         * Egy-két szó, pl. „Csukló".
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Legfeljebb 2 gomb. Az ELSŐ a hangsúlyos (ez vigyen a kurzusokhoz), a második visszafogottabb. Ha üresen hagyod, nem jelenik meg gomb.
   */
  ctas?:
    | {
        /**
         * Ez a szöveg jelenik meg a gombon (pl. „Kurzusok megtekintése").
         */
        felirat: string;
        /**
         * Saját oldalra elég a perjellel kezdődő rész (pl. /kurzusok), másik weboldalra a teljes cím https://-sel kezdve.
         */
        url: string;
        /**
         * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
         */
        ujAblakban?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'filmHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCredsStrip".
 */
export interface BlockCredsStrip {
  /**
   * Rövid, tényszerű állítások egymás mellett (pl. „Gyógytornász és manuálterapeuta szakmai háttér"). 2–4 tétel a legjobb; a hosszú mondatok itt elvesznek.
   */
  items?:
    | {
        /**
         * Egy tömör mondatrész, pont nélkül.
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Nem kötelező. Ide szokott kerülni a „Bővebben a szakmai hátterünkről" hivatkozás a Rólunk oldalra.
   */
  link?: {
    /**
     * Ez a szöveg jelenik meg a gombon (pl. „Kurzusok megtekintése").
     */
    felirat?: string | null;
    /**
     * Saját oldalra elég a perjellel kezdődő rész (pl. /kurzusok), másik weboldalra a teljes cím https://-sel kezdve.
     */
    url?: string | null;
    /**
     * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
     */
    ujAblakban?: boolean | null;
  };
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'credsStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCourseCards".
 */
export interface BlockCourseCards {
  /**
   * Nem kötelező. Ha üresen hagyod, a beépített cím marad („Így tudunk neked segíteni").
   */
  heading?: string | null;
  /**
   * A cím alatti 1–2 mondat a kártyák előtt. Nem kötelező.
   */
  lead?: string | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'courseCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFreeSos".
 */
export interface BlockFreeSos {
  /**
   * A sáv címe (pl. „SOS KézRelax villámkurzus").
   */
  title: string;
  /**
   * Pár mondat arról, mit kap a látogató az ingyenes anyagban.
   */
  body?: string | null;
  /**
   * A sáv gombja — ez visz az ingyenes kurzushoz.
   */
  cta?: {
    /**
     * Ez a szöveg jelenik meg a gombon (pl. „Kurzusok megtekintése").
     */
    felirat?: string | null;
    /**
     * Saját oldalra elég a perjellel kezdődő rész (pl. /kurzusok), másik weboldalra a teljes cím https://-sel kezdve.
     */
    url?: string | null;
    /**
     * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
     */
    ujAblakban?: boolean | null;
  };
  /**
   * Nem kötelező. Halvány, nem zavaró kép a sáv mögé — a szöveg olvashatósága a fontosabb.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'freeSos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockPressLogos".
 */
export interface BlockPressLogos {
  /**
   * A logók fölötti rövid szöveg (pl. „Ismerhetsz minket innen").
   */
  heading?: string | null;
  /**
   * A logókat előbb töltsd fel a Tartalom → Képek közé, itt már csak kiválasztod őket. Átlátszó hátterű (PNG) logó néz ki a legjobban.
   */
  logos?:
    | {
        /**
         * A médium vagy szervezet logója.
         */
        image: number | Media;
        /**
         * Nem kötelező. Ha üresen hagyod, a Képek közt megadott képleírás jelenik meg — általában az a jó.
         */
        alt?: string | null;
        /**
         * Nem kötelező. A médium cikkének vagy a szervezet oldalának teljes címe https://-sel.
         */
        url?: string | null;
        /**
         * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
         */
        ujAblakban?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pressLogos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockWelcome".
 */
export interface BlockWelcome {
  /**
   * A szekció címe — jellemzően kérdés, ami a látogató helyzetét mondja ki (pl. „Szeretnél megszabadulni a fájdalomtól…?").
   */
  title: string;
  /**
   * Rövid átvezetés a felsorolás elé (pl. „Tudjuk, milyen, amikor:").
   */
  lead?: string | null;
  /**
   * A látogató ismerős helyzetei, egy-egy mondatban. 3–5 tétel a legjobb — ennél több már hosszú lista.
   */
  checklist?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A felsorolás mellé kerülő szöveg: mit tudunk kezdeni ezzel a helyzettel. A lezáró, ígéretet megfogalmazó bekezdésnél kapcsold be a „Kiemelt" pipát.
   */
  sideParagraphs?:
    | {
        text: string;
        /**
         * Vastag betűvel jelenik meg. Egy szekcióban legfeljebb egy bekezdésnél használd.
         */
        emphasized?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'welcome';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockUsps".
 */
export interface BlockUsps {
  /**
   * A kártyák fölötti cím (pl. „Erre számíthatsz velünk").
   */
  title?: string | null;
  /**
   * Legfeljebb 4 kártya. Sorrendjük fogd-és-vidd módszerrel átrendezhető.
   */
  cards?:
    | {
        /**
         * Egy tömör állítás, nem szlogen.
         */
        title: string;
        /**
         * Mit jelent ez a gyakorlatban.
         */
        body: string;
        /**
         * Nem kötelező — a részletek, példák helye.
         */
        extra?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'usps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockStates".
 */
export interface BlockStates {
  /**
   * A kártyák fölötti cím (pl. „Három állapot, egy folyamat").
   */
  title?: string | null;
  /**
   * Pár mondat arról, mit mutat a három kép. Nem kötelező.
   */
  lead?: string | null;
  /**
   * Három kártya: a zárt, a nyíló és a nyitott kéz — ebben a sorrendben. A képeket előbb töltsd fel a Tartalom → Képek közé.
   */
  cards?:
    | {
        /**
         * A kártya képe. A képleírást (alt) a Képek közt add meg egyszer.
         */
        image?: (number | null) | Media;
        /**
         * Nem kötelező. Pl. „01". Ha üresen hagyod, a rendszer maga számoz.
         */
        number?: string | null;
        /**
         * Egy szó a legjobb (pl. „Zárt", „Nyíló", „Nyitott").
         */
        title: string;
        /**
         * 1–2 mondat arról, mit jelent ez az állapot.
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'states';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockServices".
 */
export interface BlockServices {
  /**
   * A cím fölötti apró szöveg (pl. „Szolgáltatásaink"). Nem kötelező.
   */
  eyebrow?: string | null;
  /**
   * A szekció nagybetűs címe (pl. „Így tudunk segíteni").
   */
  title?: string | null;
  /**
   * A sorok mellé kerülő kép (pl. terapeuta keze munka közben). Nem kötelező — kép nélkül a sorok teljes szélességben állnak.
   */
  image?: (number | null) | Media;
  /**
   * Egy sor = egy szolgáltatás. Legfeljebb 5.
   */
  rows?:
    | {
        /**
         * Nem kötelező. Pl. „01". Ha üresen hagyod, a rendszer maga számoz.
         */
        number?: string | null;
        /**
         * A szolgáltatás neve (pl. „Rendelői kezelések").
         */
        title: string;
        /**
         * 2–4 mondat arról, kinek és miben segít.
         */
        body: string;
        /**
         * A sor végi hivatkozás szövege (pl. „Tovább a kezelésekre").
         */
        felirat?: string | null;
        /**
         * Saját oldalra elég a perjellel kezdődő rész (pl. /kurzusok), másik weboldalra a teljes cím https://-sel kezdve.
         */
        url?: string | null;
        /**
         * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
         */
        ujAblakban?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockAbout".
 */
export interface BlockAbout {
  /**
   * A cím fölötti apró szöveg (pl. „Rólunk"). Nem kötelező.
   */
  eyebrow?: string | null;
  /**
   * A bemutatkozás címe (pl. „Kiss Kata és Kocsis Kata vagyunk").
   */
  title?: string | null;
  /**
   * A bemutatkozás szövege bekezdésenként. Az első, összefoglaló bekezdésnél szokás bekapcsolni a „Kiemelt" pipát.
   */
  paragraphs?:
    | {
        text: string;
        /**
         * Vastag betűvel jelenik meg. Egy szekcióban legfeljebb egy bekezdésnél használd.
         */
        emphasized?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A bekezdések alatti, keretes kiemelés — egy fontos ígéret pár szóban. Ha mindkét mezőt üresen hagyod, nem jelenik meg.
   */
  feature?: {
    /**
     * Pl. „Személyre szabott kezelések".
     */
    label?: string | null;
    /**
     * Egy mondat a felirat alá.
     */
    note?: string | null;
  };
  /**
   * A szekció melletti fénykép. A képleírást (alt) a Képek közt add meg egyszer.
   */
  photo?: (number | null) | Media;
  /**
   * Rövid, VALÓS adatok (pl. „10+ év szakmai tapasztalat"). Kitalált számot ne írj ide.
   */
  stats?:
    | {
        /**
         * A nagy betűs szám (pl. „10+", „5000+").
         */
        value: string;
        /**
         * A szám alatti magyarázat (pl. „év szakmai tapasztalat").
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHowItWorks".
 */
export interface BlockHowItWorks {
  /**
   * A lépések fölötti cím (pl. „Így működik az online kurzus").
   */
  title?: string | null;
  /**
   * A folyamat lépései sorrendben — 3 lépés a legérthetőbb. A sorszámokat a rendszer teszi ki.
   */
  steps?:
    | {
        /**
         * Rövid, cselekvő megfogalmazás (pl. „Kiválasztod a kurzust").
         */
        title: string;
        /**
         * 1–2 mondat arról, mi történik ebben a lépésben.
         */
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'howItWorks';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockTestimonials".
 */
export interface BlockTestimonials {
  /**
   * A cím fölötti apró szöveg (pl. „Vélemények"). Nem kötelező.
   */
  eyebrow?: string | null;
  /**
   * Nem kötelező. Ha üresen hagyod, a beépített cím marad („Pácienseink mondták").
   */
  heading?: string | null;
  /**
   * Legfeljebb 3 — a kezdőlap nem lehet több képernyőnyi idézet. A megjelenő véleményeket a Tartalom → Vélemények alatt a „Kiemelt" pipa és a „Sorrend" dönti el.
   */
  maxItems?: number | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockKnowledge".
 */
export interface BlockKnowledge {
  /**
   * Nem kötelező. Ha üresen hagyod, a beépített cím marad („Legfrissebb a tudástárból").
   */
  heading?: string | null;
  /**
   * 1 és 6 közötti szám. A kezdőlapon 3 a szokásos.
   */
  limit?: number | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'knowledge';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFaq".
 */
export interface BlockFaq {
  /**
   * A kérdések fölötti cím (pl. „Gyakori kérdések").
   */
  heading?: string | null;
  /**
   * A látogatók tényleges kérdései, a válasszal együtt. Ezekből készül a Google-nek szóló strukturált adat is, ezért ide csak sima szöveg kerüljön — formázás és link nélkül.
   */
  items?:
    | {
        /**
         * Úgy fogalmazd, ahogy a látogató kérdezné (pl. „Műtét után is végezhetem a gyakorlatokat?").
         */
        question: string;
        /**
         * Rövid, egyértelmű válasz 2–4 mondatban. Gyógyulást ne ígérj; műtét utáni kérdésnél utalj a kezelőorvos jóváhagyására.
         */
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockRichText".
 */
export interface BlockRichText {
  /**
   * Szabadon szerkeszthető szöveg. A felső eszköztárral formázhatsz, listát és linket szúrhatsz be.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCtaBanner".
 */
export interface BlockCtaBanner {
  /**
   * Egy rövid, cselekvésre hívó mondat.
   */
  title: string;
  /**
   * Nem kötelező. Egy-két mondat a cím alá.
   */
  text?: string | null;
  /**
   * A sáv gombja. Felirat és cím nélkül a sáv gomb nélkül jelenik meg.
   */
  cta?: {
    /**
     * Ez a szöveg jelenik meg a gombon (pl. „Kurzusok megtekintése").
     */
    felirat?: string | null;
    /**
     * Saját oldalra elég a perjellel kezdődő rész (pl. /kurzusok), másik weboldalra a teljes cím https://-sel kezdve.
     */
    url?: string | null;
    /**
     * Másik weboldalra mutató linknél szokás bekapcsolni, hogy a látogató ne hagyja el a Kineticare oldalát.
     */
    ujAblakban?: boolean | null;
  };
  /**
   * Megjelenés és elrejtés — a szekció szövegét fölötte szerkesztheted.
   */
  sectionSettings?: {
    /**
     * Ha kiveszed a pipát, a szekció eltűnik az oldalról, de a tartalma megmarad — bármikor visszakapcsolhatod.
     */
    visible?: boolean | null;
    /**
     * Nem kötelező. Rövid azonosító a lapon belüli ugráshoz (pl. „kurzusok"): ezután a szekcióra a webcím végére írt #kurzusok résszel lehet hivatkozni. Csak ékezet nélküli kisbetű, szám és kötőjel; a # jelet ne írd bele.
     */
    anchorId?: string | null;
    /**
     * A szekció háttérsávja. Váltogasd a fehéret és a világoskéket, hogy az egymás alatti szekciók jól elkülönüljenek; a sötétkéket ritkán, kiemelésre használd.
     */
    hatter?: ('feher' | 'tint' | 'sotet') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * A Tudástár (blog) cikkei. A közzétett bejegyzések azonnal megjelennek az oldalon.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * A bejegyzés címe — ez jelenik meg a listában és a Google találatai közt.
   */
  title: string;
  /**
   * A cím webcímes alakja, magától kitöltődik (ékezetek nélkül, kötőjelekkel). Csak akkor írd át, ha tudod, mit csinálsz — a régi webcím ilyenkor megszűnik működni.
   */
  slug: string;
  /**
   * Pár mondatos ajánló; a bloglista kártyáin és a Google-ban is ez látszik.
   */
  excerpt?: string | null;
  /**
   * A cikk szövege. A felső eszköztárral formázhatsz, listázhatsz, linkelhetsz.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * A cikk fő képe — a bloglistán és a cikk tetején jelenik meg.
   */
  heroImage?: (number | null) | Media;
  /**
   * Ha üresen hagyod, a Google a fenti címet használja.
   */
  seoTitle?: string | null;
  /**
   * A Google találati listáján megjelenő rövid leírás (kb. 150 karakter).
   */
  seoDescription?: string | null;
  /**
   * Ez a kép jelenik meg, ha valaki Facebookon vagy Messengeren megosztja a cikket.
   */
  ogImage?: (number | null) | Media;
  status: 'draft' | 'published';
  /**
   * Az első közzétételkor magától kitöltődik. A bloglista ez alapján rendez (a legfrissebb elöl).
   */
  publishedAt?: string | null;
  /**
   * A lista- és menürendezéshez használt sorszám (kisebb = előrébb).
   */
  order?: number | null;
  /**
   * Alapból te vagy; ha más nevében írod a cikket, itt átállíthatod.
   */
  author?: (number | null) | User;
  /**
   * Melyik témakörökbe tartozik a cikk. Több is választható.
   */
  categories?: (number | Category)[] | null;
  /**
   * Legfeljebb 3 cikk, amit a bejegyzés alján ajánlunk az olvasónak.
   */
  relatedPosts?: (number | Post)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Szerkesztők és vásárlók. A szerepkört csak tulajdonos állíthatja át.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Tulajdonos: mindent lát és állít. Munkatárs: tartalmat kezel. Vásárló: csak a saját fiókját. Átállítani csak tulajdonos tud.
   */
  role: 'owner' | 'staff' | 'customer';
  /**
   * A felhasználó által megvásárolt kurzusok (hozzáférés). A fizetés után magától töltődik — kézzel nem szerkeszthető.
   */
  purchases?: (number | Product)[] | null;
  billingName?: string | null;
  billingZip?: string | null;
  billingCity?: string | null;
  billingStreet?: string | null;
  /**
   * Csak céges vásárlásnál kell.
   */
  taxNumber?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A megvásárolható kurzusok. Az árat és a közzétételt csak tulajdonos állíthatja.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  inventory?: number | null;
  priceInHUFEnabled?: boolean | null;
  priceInHUF?: number | null;
  /**
   * A kurzus címe, ahogy a látogató látja (pl. „Kéztorna otthon — 8 hetes program"). Ebből készül a webcím is. Ha üresen hagyod, a lenti „Kurzus neve (azonosító)" jelenik meg.
   */
  displayTitle?: string | null;
  /**
   * A kurzus webcíme (pl. kezrehabilitacio-otthon). Magától kitöltődik a kurzus címéből, ékezetek nélkül, kötőjelekkel; ha a webcím már foglalt, sorszám kerül a végére. Csak akkor írd át, ha tudod, mit csinálsz — a régi webcím ilyenkor megszűnik működni.
   */
  slug?: string | null;
  /**
   * 1–3 mondat. A kurzuskártyákon és a kezdőlapon ez látszik.
   */
  shortDescription?: string | null;
  /**
   * A kurzus oldalán megjelenő teljes szöveg.
   */
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A kurzus kártyáján és az oldala tetején megjelenő kép.
   */
  coverImage?: (number | null) | Media;
  /**
   * További képek a kurzus oldalára (nem kötelező).
   */
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ha üresen hagyod, a Google a kurzus nevét használja.
   */
  seoTitle?: string | null;
  /**
   * A Google találati listáján megjelenő rövid leírás (kb. 150 karakter).
   */
  seoDescription?: string | null;
  /**
   * Ez a kép jelenik meg, ha valaki Facebookon vagy Messengeren megosztja a kurzust.
   */
  ogImage?: (number | null) | Media;
  /**
   * Kötelező. Ha nincs megfelelő, előbb hozd létre a Tartalom → Kategóriák alatt.
   */
  category: number | Category;
  /**
   * Ez dönti el, hogy a Kurzusok oldalon melyik sávban jelenik meg: „Otthoni gyakorlóknak" vagy „Szakembereknek". Ha üresen marad, az otthoni sávba kerül.
   */
  audience?: ('laikus' | 'szakember') | null;
  /**
   * Az ingyenes előzetes Bunny videó GUID-ja — a PUBLIKUS (jegy nélküli) libraryből, a Bunny felületén a videó adatlapján található. Ha nem tudod, hagyd üresen.
   */
  previewVideoStreamId?: string | null;
  /**
   * A kurzus videói — a vásárlók ezeket nézhetik meg.
   */
  videos?:
    | {
        title?: string | null;
        /**
         * A Bunny Stream videó GUID-ja — a VÉDETT libraryből, a Bunny felületén a videó adatlapján található. Kézzel másolandó be.
         */
        streamAssetId?: string | null;
        durationSec?: number | null;
        /**
         * A videó feldolgozottsága. Nincs feltöltő-automatizmus, ezért KÉZZEL kell „Kész"-re állítani, miután a Bunny végzett a feldolgozással — csak a Kész állapotú videó játszható le.
         */
        status?: ('processing' | 'ready' | 'error') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hány napig érvényes a hozzáférés vásárlás után. Üres (null) = örök hozzáférés.
   */
  accessDurationDays?: number | null;
  /**
   * Csak a közzétett kurzus látszik az oldalon. Ezt csak tulajdonos állíthatja.
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * A kurzus egyedi azonosítója — két kurzusnak nem lehet ugyanaz. Ez jelenik meg a rendeléseken és a számlán. Ha a fenti „Kurzus címe" üres, a látogató is ezt látja.
   */
  sku?: string | null;
  /**
   * A kurzus oldalán ajánlott további kurzusok.
   */
  relatedProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Témakörök a blogbejegyzésekhez és a kurzusokhoz.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * A kategória neve, ahogy az olvasó látja (pl. „Kézrehabilitáció").
   */
  title: string;
  /**
   * A cím webcímes alakja, magától kitöltődik (ékezetek nélkül, kötőjelekkel). Csak akkor írd át, ha tudod, mit csinálsz — a régi webcím ilyenkor megszűnik működni.
   */
  slug: string;
  /**
   * Blogkategória a Tudástár cikkeihez, kurzuskategória a webshop termékeihez. A blog csak a blogkategóriákat mutatja.
   */
  type?: ('content' | 'product') | null;
  /**
   * Csak akkor töltsd ki, ha ez egy nagyobb témakör alkategóriája.
   */
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * Páciensek valódi visszajelzései. A kezdőlapon legfeljebb 3 kiemelt vélemény jelenik meg.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * A vélemény teljes, eredeti szövege — pontosan úgy, ahogy elhangzott.
   */
  quote: string;
  /**
   * Rövid, 1–2 mondatos változat a főoldalra (legfeljebb 260 karakter). Ha üresen hagyod, a kezdőlapon a TELJES szöveg jelenik meg — hosszú véleménynél ezért töltsd ki.
   */
  shortQuote?: string | null;
  /**
   * Aki a véleményt mondta (pl. „Garami Gábor" vagy „P. Benjámin").
   */
  authorName: string;
  /**
   * Nem kötelező — pl. „zenész, műsorvezető".
   */
  authorTitle?: string | null;
  /**
   * Főoldalon megjelenik (a Sorrend szerinti első 3 kiemelt). Kiemeléshez rövid változat kell, vagy elég rövid teljes szöveg.
   */
  featured?: boolean | null;
  /**
   * A megjelenés sorrendje (kisebb szám = előrébb).
   */
  order?: number | null;
  /**
   * Ha kiveszed a pipát, a vélemény sehol nem jelenik meg, de nem vész el.
   */
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Az oldal tetején látszó menü. Legfeljebb 2 szint: főmenüpont és alatta almenüpontok.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  /**
   * Ez a szöveg jelenik meg a menüben (pl. „Kurzusok").
   */
  label: string;
  /**
   * Válaszd ki, milyen tartalomra visz a menüpont; ettől függ a következő mező.
   */
  type: 'page' | 'post' | 'url' | 'product';
  /**
   * A menüpont célja — a fent választott típusnak megfelelő listából.
   */
  ref?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  /**
   * Teljes webcím más oldalra, https://-sel kezdve.
   */
  url?: string | null;
  /**
   * Csak akkor töltsd ki, ha ez almenüpont. Legfeljebb 2 szintű a menü: almenüpont alá már nem tehetsz továbbit.
   */
  parent?: (number | null) | Menu;
  /**
   * A menün belüli sorrend (kisebb szám = előrébb).
   */
  order?: number | null;
  /**
   * Ha kiveszed a pipát, a menüpont eltűnik az oldalról, de nem vész el.
   */
  visible?: boolean | null;
  /**
   * Külső linkeknél szokás bekapcsolni, hogy a látogató ne hagyja el az oldalt.
   */
  openInNewTab?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ki melyik kurzus melyik videóját nézte meg. A rendszer tölti a lejátszóból — kézzel nem szerkeszthető, hibás sor törölhető.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress".
 */
export interface CourseProgress {
  id: number;
  user: number | User;
  product: number | Product;
  /**
   * A videó STABIL azonosítója (a CMS-sor id-ja, ennek hiányában a Bunny videó GUID-ja). Sorszám sosem kerül ide.
   */
  videoRef: string;
  /**
   * A megjelölés időpontja — kizárólag a szerver állítja.
   */
  watchedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * A vásárlók félbehagyott kosarai. Automatikusan keletkezik — ne szerkeszd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'HUF' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A leadott rendelések és a fizetésük állapota. A rendeléseket a rendszer kezeli — kézzel ne módosítsd őket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        /**
         * A termék azonosító-neve (sku) a megrendeléskor. SZÁNDÉKOSAN a sku, nem a kurzuscím (displayTitle): a rendelés- és számlasoron a stabil azonosító a hasznos, a marketingcím változhat.
         */
        titleSnapshot?: string | null;
        /**
         * A termék priceInHUF értéke a megrendeléskor (szerver-oldali forrás).
         */
        priceHufSnapshot?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'HUF' | null;
  /**
   * Szerver-oldalon generált rendelésszám (KH-<év>-<6 jegyű sorszám>); create-kor töltődik, update-kor sosem számolódik újra.
   */
  orderNumber?: string | null;
  /**
   * A rendelés végösszege a megrendeléskor (az item-snapshotok ár × mennyiség összege). A plugin amount mezője ugyanezt tükrözi.
   */
  totalHufSnapshot?: number | null;
  /**
   * A Barion oldali fizetés azonosítója — hibakereséshez.
   */
  barionPaymentId?: string | null;
  barionPaymentRequestId?: string | null;
  invoiceNumber?: string | null;
  invoicePdfUrl?: string | null;
  /**
   * A számlázás állapota. A rendszer állítja — ne írd át.
   */
  invoiceStatus?: ('none' | 'pending' | 'issued' | 'failed') | null;
  /**
   * A számlakiállítási kísérletek száma (legfeljebb 5, utána emberi beavatkozás kell). A rendszer állítja.
   */
  invoiceAttempts?: number | null;
  /**
   * Az utolsó sikertelen számlakiállítási kísérlet hibaüzenete — hibakereséshez.
   */
  invoiceLastError?: string | null;
  /**
   * Az eredeti számla teljesítési dátuma (ÉÉÉÉ-HH-NN) — a helyesbítő számla ezt ismétli meg. A rendszer állítja.
   */
  invoiceCompletionDate?: string | null;
  /**
   * A stornó-számla állapota. A rendszer állítja — ne írd át.
   */
  stornoStatus?: ('none' | 'pending' | 'storned' | 'failed') | null;
  stornoNumber?: string | null;
  /**
   * A stornó-kiállítási kísérletek száma (legfeljebb 5, utána emberi beavatkozás kell). A rendszer állítja.
   */
  stornoAttempts?: number | null;
  /**
   * Az utolsó sikertelen stornó-kísérlet hibaüzenete — hibakereséshez.
   */
  stornoLastError?: string | null;
  /**
   * A helyesbítő (módosító) számla állapota. A rendszer állítja — ne írd át.
   */
  correctiveInvoiceStatus?: ('none' | 'pending' | 'issued' | 'failed') | null;
  correctiveInvoiceNumber?: string | null;
  /**
   * A refunds-nyom hányadik bejegyzéséhez tartozik a legutóbbi helyesbítő számla (idempotencia). A rendszer állítja.
   */
  correctiveInvoiceSeq?: number | null;
  /**
   * A helyesbítő-kiállítási kísérletek száma (legfeljebb 5, utána emberi beavatkozás kell). A rendszer állítja.
   */
  correctiveInvoiceAttempts?: number | null;
  /**
   * Az utolsó sikertelen helyesbítő-kísérlet hibaüzenete — hibakereséshez.
   */
  correctiveInvoiceLastError?: string | null;
  /**
   * Melyik refund-sorszámú helyesbítőhöz tartozik a kísérletszámláló. A rendszer állítja.
   */
  correctiveInvoiceAttemptsSeq?: number | null;
  /**
   * A számlázási adatok mentett másolata a rendelés idejéből.
   */
  customerSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * A vásárló a megrendeléskor kérte az azonnali hozzáférést, és tudomásul vette, hogy ezzel elveszti a 14 napos elállási jogát.
   */
  consentWithdrawalWaiver?: boolean | null;
  consentWithdrawalWaiverAt?: string | null;
  refundReason?: string | null;
  refundedAt?: string | null;
  /**
   * Visszatérítési nyom: tranzakciós refund-bejegyzések (transactionId, összeg, Barion-státusz, időpont, típus).
   */
  refunds?:
    | {
        transactionId: string;
        amountHuf: number;
        status: string;
        refundedAt: string;
        type: 'full' | 'partial';
        reason?: string | null;
      }[]
    | null;
  /**
   * A megrendelés IP-címe — csalásgyanús eset kivizsgálásához.
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A fizetési tranzakciók nyoma. Csak a rendszer írja — ne szerkeszd.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'HUF' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A weboldal űrlapjai (pl. Kapcsolat). A mezőket itt lehet átszabni.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A látogatók által beküldött üzenetek. Csak olvasásra való.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cloudflare Turnstile spam-ellenőrző token — csak akkor kötelező, ha a TURNSTILE_SECRET_KEY be van állítva.
   */
  turnstileToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A fizetési és videós szolgáltatók értesítései — hibakereséshez. Ide nem kell nyúlni.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: 'barion' | 'stream' | 'szamlazz';
  externalId: string;
  eventType?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'received' | 'processed' | 'failed';
  attempts?: number | null;
  lastError?: string | null;
  requestId?: string | null;
  /**
   * A sikeres/végleges feldolgozás időpontja. Hiba (failed) esetén szándékosan üres — az esemény újrapróbálható marad.
   */
  processedAt?: string | null;
  /**
   * Az utolsó feldolgozás üzleti kimenetele. A „Függő" azt jelenti, hogy a fizetés még nem dőlt el: a rendszer később magától újra rákérdez a szolgáltatónál.
   */
  result?: ('paid' | 'cancelled' | 'pending_repoll' | 'rejected' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ki, mikor, mit módosított a pénzügyi és jogosultsági műveletekben. Csak olvasható.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  entityType?: string | null;
  entityId?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'webhook-retry' | 'order-poll' | 'invoice-issue' | 'storno-issue' | 'corrective-invoice-issue';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'webhook-retry' | 'order-poll' | 'invoice-issue' | 'storno-issue' | 'corrective-invoice-issue') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'course-progress';
        value: number | CourseProgress;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        xs?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  layout?:
    | T
    | {
        filmHero?: T | BlockFilmHeroSelect<T>;
        credsStrip?: T | BlockCredsStripSelect<T>;
        courseCards?: T | BlockCourseCardsSelect<T>;
        freeSos?: T | BlockFreeSosSelect<T>;
        pressLogos?: T | BlockPressLogosSelect<T>;
        welcome?: T | BlockWelcomeSelect<T>;
        usps?: T | BlockUspsSelect<T>;
        states?: T | BlockStatesSelect<T>;
        services?: T | BlockServicesSelect<T>;
        about?: T | BlockAboutSelect<T>;
        howItWorks?: T | BlockHowItWorksSelect<T>;
        testimonials?: T | BlockTestimonialsSelect<T>;
        knowledge?: T | BlockKnowledgeSelect<T>;
        faq?: T | BlockFaqSelect<T>;
        richText?: T | BlockRichTextSelect<T>;
        ctaBanner?: T | BlockCtaBannerSelect<T>;
      };
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  status?: T;
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFilmHero_select".
 */
export interface BlockFilmHeroSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctas?:
    | T
    | {
        felirat?: T;
        url?: T;
        ujAblakban?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCredsStrip_select".
 */
export interface BlockCredsStripSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  link?:
    | T
    | {
        felirat?: T;
        url?: T;
        ujAblakban?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCourseCards_select".
 */
export interface BlockCourseCardsSelect<T extends boolean = true> {
  heading?: T;
  lead?: T;
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFreeSos_select".
 */
export interface BlockFreeSosSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  cta?:
    | T
    | {
        felirat?: T;
        url?: T;
        ujAblakban?: T;
      };
  backgroundImage?: T;
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockPressLogos_select".
 */
export interface BlockPressLogosSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        image?: T;
        alt?: T;
        url?: T;
        ujAblakban?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockWelcome_select".
 */
export interface BlockWelcomeSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  checklist?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sideParagraphs?:
    | T
    | {
        text?: T;
        emphasized?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockUsps_select".
 */
export interface BlockUspsSelect<T extends boolean = true> {
  title?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        extra?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockStates_select".
 */
export interface BlockStatesSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  cards?:
    | T
    | {
        image?: T;
        number?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockServices_select".
 */
export interface BlockServicesSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  image?: T;
  rows?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        felirat?: T;
        url?: T;
        ujAblakban?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockAbout_select".
 */
export interface BlockAboutSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        emphasized?: T;
        id?: T;
      };
  feature?:
    | T
    | {
        label?: T;
        note?: T;
      };
  photo?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockHowItWorks_select".
 */
export interface BlockHowItWorksSelect<T extends boolean = true> {
  title?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockTestimonials_select".
 */
export interface BlockTestimonialsSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  maxItems?: T;
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockKnowledge_select".
 */
export interface BlockKnowledgeSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockFaq_select".
 */
export interface BlockFaqSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockRichText_select".
 */
export interface BlockRichTextSelect<T extends boolean = true> {
  content?: T;
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockCtaBanner_select".
 */
export interface BlockCtaBannerSelect<T extends boolean = true> {
  title?: T;
  text?: T;
  cta?:
    | T
    | {
        felirat?: T;
        url?: T;
        ujAblakban?: T;
      };
  sectionSettings?:
    | T
    | {
        visible?: T;
        anchorId?: T;
        hatter?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  status?: T;
  publishedAt?: T;
  order?: T;
  author?: T;
  categories?: T;
  relatedPosts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  shortQuote?: T;
  authorName?: T;
  authorTitle?: T;
  featured?: T;
  order?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  ref?: T;
  url?: T;
  parent?: T;
  order?: T;
  visible?: T;
  openInNewTab?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progress_select".
 */
export interface CourseProgressSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  videoRef?: T;
  watchedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  inventory?: T;
  priceInHUFEnabled?: T;
  priceInHUF?: T;
  displayTitle?: T;
  slug?: T;
  shortDescription?: T;
  longDescription?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  category?: T;
  audience?: T;
  previewVideoStreamId?: T;
  videos?:
    | T
    | {
        title?: T;
        streamAssetId?: T;
        durationSec?: T;
        status?: T;
        id?: T;
      };
  accessDurationDays?: T;
  status?: T;
  sku?: T;
  relatedProducts?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        titleSnapshot?: T;
        priceHufSnapshot?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  orderNumber?: T;
  totalHufSnapshot?: T;
  barionPaymentId?: T;
  barionPaymentRequestId?: T;
  invoiceNumber?: T;
  invoicePdfUrl?: T;
  invoiceStatus?: T;
  invoiceAttempts?: T;
  invoiceLastError?: T;
  invoiceCompletionDate?: T;
  stornoStatus?: T;
  stornoNumber?: T;
  stornoAttempts?: T;
  stornoLastError?: T;
  correctiveInvoiceStatus?: T;
  correctiveInvoiceNumber?: T;
  correctiveInvoiceSeq?: T;
  correctiveInvoiceAttempts?: T;
  correctiveInvoiceLastError?: T;
  correctiveInvoiceAttemptsSeq?: T;
  customerSnapshot?: T;
  consentWithdrawalWaiver?: T;
  consentWithdrawalWaiverAt?: T;
  refundReason?: T;
  refundedAt?: T;
  refunds?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  turnstileToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  purchases?: T;
  billingName?: T;
  billingZip?: T;
  billingCity?: T;
  billingStreet?: T;
  taxNumber?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  externalId?: T;
  eventType?: T;
  payload?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  requestId?: T;
  processedAt?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  before?: T;
  after?: T;
  requestId?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskWebhook-retry".
 */
export interface TaskWebhookRetry {
  input?: unknown;
  output: {
    scanned: number;
    retried: number;
    succeeded: number;
    failed: number;
    skipped: number;
    exhausted: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskOrder-poll".
 */
export interface TaskOrderPoll {
  input?: unknown;
  output: {
    scanned: number;
    transitionedPaid: number;
    cancelled: number;
    stillPending: number;
    skipped: number;
    failed: number;
    orphaned: number;
    invoiceRequeued: number;
    invoiceResweep: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskInvoice-issue".
 */
export interface TaskInvoiceIssue {
  input: {
    orderId: number;
  };
  output: {
    outcome: string;
    invoiceNumber?: string | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskStorno-issue".
 */
export interface TaskStornoIssue {
  input: {
    orderId: number;
  };
  output: {
    outcome: string;
    stornoNumber?: string | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCorrective-invoice-issue".
 */
export interface TaskCorrectiveInvoiceIssue {
  input: {
    orderId: number;
    refundSeq: number;
  };
  output: {
    outcome: string;
    correctiveInvoiceNumber?: string | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}